name: Test Input
description: Test input
inputs:
  my_input: 
    description: My input
    required: false
    default: 'foobar'

runs:
  using: 'composite'
  steps:
    - name: Log input val
      uses: actions/github-script@v6
      with:
        script: |
          console.log('my_input =', core.getInput('my_input'))
    - name: Log it the other way
      run: |
        echo ${{ inputs.my_input }}
      shell: bash
    - name: Show env
      run: |
        env
      shell: bash
    - name: Try it by using process.env
      run: |
        export ACTION_MY_INPUT = "${{ inputs.my_input }}"
      shell: bash
    - name: Log ACTION_MY_INPUT
      uses: actions/github-script@v6
      with:
        script: |
          console.log('ACTION_MY_INPUT =', process.env.ACTION_MY_INPUT)